import { useState } from 'react'

// moved BlogForm into its own component
// and the states related to it
const BlogForm = ({createBlog}) => {

  // add state for title, author and url
  const [newTitle, setNewTitle] = useState('') // newTitle state reflects current value of title input
  const [newAuthor, setNewAuthor] = useState('') // newTitle state reflects current value of author input
  const [newUrl, setNewUrl] = useState('') // newTitle state reflects current value of url input

  const handleSubmit = (event) => {
    event.preventDefault()

    console.log('button clicked', event.target)
    
    createBlog({
      title: newTitle,
      author: newAuthor,
      url: newUrl,
      // likes is set to 0
      // id is generated by server
    })

    // reset fields (not rlly needed since the form is hidden)
    setNewTitle('')
    setNewAuthor('')
    setNewUrl('')
  }

    
  // move h2 to correct position so it gets toggled as well with the form
  return (
    <div>
      <h2>create new</h2>
      <form onSubmit={handleSubmit}>
        <div>
          title:
          <input
            value={newTitle}
            onChange={({target}) => setNewTitle(target.value)}
          />
        </div>
        <div>
          author:
          <input
            value={newAuthor}
            onChange={({target}) => setNewAuthor(target.value)}
          />
        </div>
        <div>
          url:
          <input
            value={newUrl}
            onChange={({target}) => setNewUrl(target.value)}
          />
        </div>
        <button type="submit">create</button>
      </form>
    </div>  
  )
}

export default BlogForm