POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1kYW4yMiIsImlkIjoiNjZmYTk1YWQzZTczMzRlMWUyNjY0NTRjIiwiaWF0IjoxNzI3Njk4NDI0fQ.-GSsWAE0F2cB6dY-nsogepMFycdxhDJNMpMddvhYuRA

{
    "title": "Another Test Blog",
    "author": "Mdan22",
    "url": "mdan22.me",
    "likes": 0,
    "userId": "66f3d2004c716edac78b4ac7"
}