import loginService from './services/login'

import { useState, useEffect } from 'react'
import Blog from './components/Blog'
import blogService from './services/blogs'

const App = () => {
  const [blogs, setBlogs] = useState([])
  // add state for title, author and url
  const [newTitle, setNewTitle] = useState('') // newTitle state reflects current value of title input
  const [newAuthor, setNewAuthor] = useState('') // newTitle state reflects current value of author input
  const [newUrl, setNewUrl] = useState('') // newTitle state reflects current value of url input
  // add state for username and password
  const [username, setUsername] = useState('') 
  const [password, setPassword] = useState('')
  const [user, setUser] = useState(null)

  // effect hooks should be put at beginning lol
  useEffect(() => {
    blogService.getAll().then(blogs =>
      setBlogs( blogs )
    )  
  }, [])

  // add effect hook for checking local storage of browser for user data
  // and set user to logged in state if data was found 
  useEffect(() => {
    const loggedUserJSON = window.localStorage.getItem('loggedBlogAppUser')
    if (loggedUserJSON) {
      const user = JSON.parse(loggedUserJSON)
      setUser(user)
      blogService.setToken(user.token)
    }
  }, [])

  // outsource login form
  const loginForm = () => (
    <form onSubmit={handleLogin}>
      <div>
        username
          <input
          type="text"
          value={username}
          name="Username"
          onChange={({ target }) => setUsername(target.value)}
        />
      </div>
      <div>
        password
          <input
          type="password"
          value={password}
          name="Password"
          onChange={({ target }) => setPassword(target.value)}
        />
      </div>
      <button type="submit">login</button>
    </form>      
  )

  // outsource blog form
  // simply add a form with 3 fields + 1 button
  // title, author, url
  const blogForm = () => (
    <form onSubmit={addBlog}>
      <div>
        title:
        <input
          value={newTitle}
          onChange={handleTitleChange}
        />
      </div>
      <div>
        author:
        <input
          value={newAuthor}
          onChange={handleAuthorChange}
        />
      </div>
      <div>
        url:
        <input
          value={newUrl}
          onChange={handleUrlChange}
        />
      </div>
      <button type="submit">create</button>
    </form>  
  )

  // outsource logout form
  // simple - it's just a logout button
  const logoutForm = () => (
    <button onClick={handleLogout}>logout</button>
  )

  // outsource blog list
  const blogList = () => {
    return (
      <div>
        {blogs.map(blog =>
        <Blog key={blog.id} blog={blog} />
      )}
      </div>
    )
  }

  const handleLogin = async (event) => {
    event.preventDefault()
    
    try {
      const user = await loginService.login({
        username, password,
      })

      // add user data to local storage of browser
      window.localStorage.setItem(
        'loggedBlogAppUser', JSON.stringify(user)
      )

      blogService.setToken(user.token)
      setUser(user)
      setUsername('')
      setPassword('')
    } catch (exception) {
      // we could put an error message like this:
      // setErrorMessage('Wrong credentials')
      // setTimeout(() => {
      //   setErrorMessage(null)
      // }, 5000)
      console.log(exception)
    }
  }

  // handler sets user and token to null and
  // removes local storage data of user in browser
  const handleLogout = async (event) => {
    event.preventDefault()
    
    try {
      window.localStorage.removeItem('loggedBlogAppUser')

      blogService.setToken(null)
      setUser(null)
    } catch (exception) {
      // we could put an error message like this:
      // setErrorMessage('Wrong credentials')
      // setTimeout(() => {
      //   setErrorMessage(null)
      // }, 5000)
      console.log(exception)
    }
  }

  // add handlers for changes in text fields
  const handleTitleChange = (event) => {
    console.log(event.target.value)
    setNewTitle(event.target.value)
  }
  const handleAuthorChange = (event) => {
    console.log(event.target.value)
    setNewAuthor(event.target.value)
  }
  const handleUrlChange = (event) => {
    console.log(event.target.value)
    setNewUrl(event.target.value)
  }

  // add handler for adding blog to server
  // using async / await syntax
  const addBlog = async (event) => {
    event.preventDefault()
    console.log('button clicked', event.target);
    // set object fields to states captured by txt fields
    const blogObject = {
      title: newTitle,
      author: newAuthor,
      url: newUrl,
      // likes is set to 0 + id is generated by server
    }
    // send Object to server
    const returnedBlogs = await blogService.create(blogObject)
    setBlogs(blogs.concat(returnedBlogs))
    setNewTitle('')
    setNewAuthor('')
    setNewUrl('')
  }

  return (
    <div>
      <h2>blogs</h2>

      {/* render login or (logout form + blog form + blog list) conditionally */}
      {user === null ?
        loginForm() :
        <div>
          <p>{user.name} logged-in{logoutForm()}</p>

          <h2>create new</h2>
          
          {blogForm()}
          {blogList()}
        </div>
      }

    </div>
  )
}

export default App